# Documentation https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md 

os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
    
notARepository: 'skip'  # Skip if there's no `git` repository in current folder
