#!/bin/bash

# Download and install the latest version of neovim
# https://github.com/neovim/neovim
#
# We can't download it directly from PPA, because it's not been updated...

# Make sure we start this script with sudo/root
if [[ $EUID -ne 0 ]]; then
	echo "neovim install.sh must be run as root"
	exit 1
fi

# Version 0.9.5
DOWNLOAD_URL=$(
	curl -s https://api.github.com/repos/neovim/neovim/releases/tags/v0.9.5 |
		grep "browser_download_url" |
		grep "nvim.appimage\"$" |
		cut -d '"' -f 4
)

curl -sLO "$DOWNLOAD_URL" &&
	cp -f nvim.appimage /usr/local/bin/vim &&
	chmod +x /usr/local/bin/vim &&
	rm -f nvim.appimage

# Note: Probably don't need these one anymore?
# # Install fg for telescope
# curl -sLO "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb"
# dpkg --install --force-overwrite ripgrep_13.0.0_amd64.deb
# rm -f ripgrep_13.0.0_amd64.deb

# Install fd for telescope
# curl -sLO "https://github.com/sharkdp/fd/releases/download/v8.4.0/fd-musl_8.4.0_amd64.deb"
# dpkg --install --force-overwrite fd-musl_8.4.0_amd64.deb
# rm -f fd-musl_8.4.0_amd64.deb
