set-option -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# ---------- OPTIONS ----------

# Fix Escape key time
set -s escape-time 0

# More time for messages
set -g display-time 2000

# Expand history
set -g history-limit 50000

# Enable Mouse
set -g mouse on

# Start windows from index 1
set -g base-index 1
setw -g pane-base-index 1

# renumber windows when a window is closed
set -g renumber-windows on

# Terminal title
set -g set-titles on
set -g set-titles-string '#{window_name}'

set -g pane-border-style fg='#565f89'
set -g pane-active-border-style fg='#7dcfff'

# Status line
setw -g status-style fg='#c0caf5',bg='#1f2335' # Status style

# Left status style
setw -g status-left ""
setw -g status-left-style fg=colour240,bg=default

# Right status style
setw -g status-right " %H:%M #h "

# Active window status
setw -g window-status-current-format " #{window_index}:#{window_name}"
setw -g window-status-current-style fg='#98c379'

# Inactive window status
setw -g window-status-format " #{window_index}:#{window_name}"
setw -g window-status-style fg='#565f89'

# ---------- KEYMAPS ----------

# Remap prefix to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Bind reload files
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Vim keys pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Windows
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Fast pane changes
bind Tab last-window
bind -r p previous-window
bind -r n next-window

# Synchronize input
bind S set-window-option synchronize-panes \; display-message "synchronize-panes #{?synchronize-panes,on,off}"

# Copy paste
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -in -selection clipboard'


# ---------- PLUGINS ----------

set -g @plugin 'tmux-plugins/tpm'

# Plugin tmux-resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

# Plugin tmux-continuum
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'
